#7 initial serverless template
kommitters/serverless-discord-bot pull request #13
Opened 2021-12-21 21:56 UTC by MarioRodriguezS

Fix #7 
## Description
The project was initialized with serverless with the aws-nodejs template and the linter was set up.

2021-12-21 22:40 UTC, estebancordoba requested changes

2021-12-21 22:40 UTC, estebancordoba commented on handler.js
> +module.exports.hello = async (event) => {
In the case that more functions are added, I think it would be better to export this way:
```
module.exports = {
   hello,
};
```
and declare the `hello` function independently before the `module.exports`:
```
const hello = (event) => {
}
```

2021-12-21 22:40 UTC, estebancordoba commented on handler.js
> +module.exports.hello = async (event) => {
It would not be necessary to specify `async` in the function since there are no promises to wait, and also since we only return a value then we can do it immediately after `=>`
```suggestion
const hello = (event) => ({
    statusCode: 200,
    body: JSON.stringify(
      {
        message: 'Go Serverless v1.0! Your function executed successfully!',
        input: event,
      },
      null,
      2,
    ),
  });
```

2021-12-22 12:38 UTC, jcamilocp requested changes

2021-12-22 12:38 UTC, jcamilocp commented on serverless.yml
> +    handler: handler.hello
This looks kind of redundant. It'd look better if we call the handler `helloFunction` or `helloHandler` and we name the function as `main` or something else. What do you think?

2021-12-22 12:38 UTC, jcamilocp commented on serverless.yml
> +  runtime: nodejs12.x
I think nodejs14.x runtime is available now on AWS

2021-12-22 12:38 UTC, jcamilocp commented
Did you test the `hello` function using `sls deploy`?

2021-12-23 23:40 UTC, merged